# Generated by Django 2.2.28 on 2023-08-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='YUIO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field0001', models.ImageField(upload_to='yuio/field0001/images/')),
                ('field2', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
